# Generated by Django 5.1.4 on 2024-12-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowManager', '0002_alter_document_owner_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
