# Generated by Django 5.1.4 on 2024-12-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowManager', '0003_alter_agent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioneddocument',
            name='workflow_elements',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
