# Generated by Django 5.1.4 on 2024-12-26 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowManager', '0004_alter_versioneddocument_workflow_elements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='current_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflowManager.versioneddocument'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='current_workflow_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflowManager.workflowelement'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflowManager.document'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='end_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='from_agent_type',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('user', 'User')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='from_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='start_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='to_agent_type',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('user', 'User')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='to_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
