# Generated by Django 5.1.4 on 2024-12-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowManager', '0006_alter_chatmessage_from_agent_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['type'], 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['creation_time'], 'verbose_name': 'Chat Message', 'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['pk'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='versioneddocument',
            options={'ordering': ['document', '-version'], 'verbose_name': 'Versioned Document', 'verbose_name_plural': 'Versioned Documents'},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['name'], 'verbose_name': 'Workflow', 'verbose_name_plural': 'Workflows'},
        ),
        migrations.AlterModelOptions(
            name='workflowelement',
            options={'ordering': ['workflow', 'position'], 'verbose_name': 'Workflow Element', 'verbose_name_plural': 'Workflow Elements'},
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='name',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='from_agent_type',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('user', 'User')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='to_agent_type',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('user', 'User')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='latest_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='versioneddocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflowelement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
