# Generated by Django 5.1.4 on 2025-01-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowManager', '0007_alter_agent_options_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowelement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowelement',
            name='relevancy_checking_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
