# Generated by Django 5.1.4 on 2025-01-22 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowManager', '0008_alter_agent_description_alter_workflow_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='current_workflow_element',
        ),
        migrations.AlterModelOptions(
            name='documentschema',
            options={'ordering': ['name'], 'verbose_name': 'Document schema', 'verbose_name_plural': 'Document schemas'},
        ),
        migrations.AlterModelOptions(
            name='versioneddocument',
            options={'ordering': ['document', '-version'], 'verbose_name': 'Versioned document', 'verbose_name_plural': 'Versioned documents'},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='workflow',
            new_name='document_schema',
        ),
        migrations.RenameField(
            model_name='versioneddocument',
            old_name='workflow_elements',
            new_name='document_elements',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='end_position',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='from_agent_type',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='in_reply_to',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='start_position',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='to_agent_type',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_user_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='llm_raw_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowManager.document')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['document'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflowManager.conversation'),
        ),
        migrations.RenameModel(
            old_name='Workflow',
            new_name='DocumentSchema',
        ),
        migrations.CreateModel(
            name='DocumentElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowManager.agent')),
                ('document_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowManager.documentschema')),
            ],
            options={
                'verbose_name': 'Document element',
                'verbose_name_plural': 'Document elements',
                'ordering': ['document_schema', 'position'],
            },
        ),
        migrations.DeleteModel(
            name='WorkflowElement',
        ),
    ]
