# Generated by Django 5.1.4 on 2025-01-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowManager', '0008_alter_agent_description_alter_workflow_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowelement',
            name='json_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
