# Generated by Django 5.1.4 on 2025-01-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowManager', '0009_workflowelement_json_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowelement',
            name='json_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
