# Generated by Django 5.1.4 on 2025-02-04 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['document'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Document schema',
                'verbose_name_plural': 'Document schemas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_version', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('current_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_document', to='orchestratorV2.conversation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestratorV2.documentschema')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestratorV2.document'),
        ),
        migrations.CreateModel(
            name='DocumentElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=255)),
                ('document_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestratorV2.documentschema')),
            ],
            options={
                'verbose_name': 'Document element',
                'verbose_name_plural': 'Document elements',
                'ordering': ['document_schema', 'position'],
            },
        ),
        migrations.CreateModel(
            name='VersionedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField()),
                ('document_elements', models.JSONField(blank=True, null=True)),
                ('html_document', models.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestratorV2.document')),
            ],
            options={
                'verbose_name': 'Versioned document',
                'verbose_name_plural': 'Versioned documents',
                'ordering': ['document', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_user_message', models.BooleanField(default=False)),
                ('from_id', models.CharField(blank=True, max_length=255, null=True)),
                ('to_id', models.CharField(blank=True, max_length=255, null=True)),
                ('llm_raw_response', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orchestratorV2.conversation')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orchestratorV2.document')),
                ('current_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orchestratorV2.versioneddocument')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['creation_time'],
            },
        ),
    ]
